import pandas as pd
import matplotlib.pyplot as plt
dataset_file ='Data.csv'
df=pd.read_csv(dataset_file)
print("File Preview :")
print(df.head())
print("Visualizing using plot :")
df.plot()
plt.title("PLOT")
plt.show()
col=input("Enter Column name to be displayed : ")
print("\n\n Scatter Plot \n\n")
plt.scatter(df.index , df[col] , color="red")
plt.xlabel("Index")
plt.ylabel(col)
plt.title("Scatter plot")
plt.show()
plt.hist(df[col],bins=10,color="blue",edgecolor="yellow")
plt.xlabel(col)
plt.ylabel("frequency")
plt.title("Histogram")
plt.show()